export default () => ({
    loading_jobs:  true,
    viewing_sessions_practice_id :'',
    viewing_jobs_locum_user_id : '',
    //PRACTICE
    practice_available_sessions: [],
    practice_available_sessions_count: 0,
    practice_applied_sessions: [],
    practice_applied_sessions_count:0,
    practice_allocated_sessions: [],
    practice_allocated_sessions_count:0,
    practice_ongoing_sessions: [],
    practice_ongoing_sessions_count: 0,
    practice_completed_sessions: [],
    practice_completed_sessions_count: 0,
    practice_unfilled_sessions: [],
    practice_unfilled_sessions_count:0,
    practice_cancelled_sessions: [],
    practice_cancelled_sessions_count:0,
    practice_declined_sessions: [],
    practice_declined_sessions_count:0,

    //LOCUM
    locum_allocated_jobs: [],
    locum_allocated_jobs_count:0,
    locum_ongoing_jobs: [],
    locum_ongoing_jobs_count:0,
    locum_available_jobs: [],
    locum_available_jobs_count:0,
    locum_matched_jobs: [],
    locum_matched_jobs_count: 0,
    locum_applied_jobs: [],
    locum_applied_jobs_count: 0,
    locum_cancelled_jobs: [],
    locum_cancelled_jobs_count: 0,
    locum_unsuccessful_jobs: [],
    locum_unsuccessful_jobs_count: 0,
    locum_declined_jobs: [],
    locum_declined_jobs_count:0,
    locum_completed_jobs: [],
    locum_completed_jobs_count:0
})